# Site settings
title: Wenlh Blog
SEOTitle: Wenlh的博客 | Wenlh Blog
header-img: img/myson.jpg
email: 66491533@qq.com
description: "我的博客,记录一下2016年学习的东西......"
keyword: "wenlh"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     wenlh
#zhihu_username:     wenlh
#github_username:    wenlh
#twitter_username:  wenlh
#facebook_username:  wenlh



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: wenlhblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "随便弄弄"
sidebar-avatar: /img/myson.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "RubyChina",
        href: "https://ruby-china.org/"
    },{
        title: "YII常用调用",
        href: "http://blog.csdn.net/xinqingch/article/details/8186745"
    },{
        title: "H-UI框架",
        href: "http://www.h-ui.net/Hui-notes-menu.shtml"
    },{
        title: "W3CSchool-PHP",
        href: "http://www.w3school.com.cn/php/php_superglobals.asp"
    },{
        title: "phpwtf.org",
        href: "http://www.phpwtf.org/"
    },{
        title: "PHP-Note",
        href: "http://www.php-note.com/"
    },{
        title: "XDITE的博客",
        href: "http://blog.xdite.net/categories/Rails/"
    }
]
